---
- name: Deploy App
  hosts: reddit-app-stage

  tasks:
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit

    - name: Reload puma
      become: true
      systemd:
        name: puma
        state: restarted
