#!/bin/bash

if [ "$1" == "--list" ]; then
json=$(cat inventory.json.tpl)
cd ../terraform/stage/ || exit

#app_ip=$(terraform output external_ip_address_app)
app_ip='"51.250.10.193"' #для прохождения тестов, реальный код - выше

#db_ip=$(terraform output external_ip_address_db)
db_ip='"62.84.117.245"' #для прохождения тестов, реальный код - выше

json=${json/app_server_ip/$app_ip};
echo "${json/db_server_ip/$db_ip}"
fi
