---
- name: Configure Packer App
  hosts: all
  become: true

  tasks:
    - name: Install Ruby and Bundler
      apt:
        name:
          - ruby-full
          - ruby-bundler
          - build-essential
        state: present
        update_cache: yes
